crud_virtual/CarritoApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('tienda/', views.tienda, name='tienda'),
    path('pagcarrito/', views.carrito, name='pagcarrito'),
    path('detalle/', views.detalle, name='detalle'),
    path('catalogos/', views.catalogo, name='catalogos'),
    path('catalogos/<str:categoria>/', views.catalogo, name='catalogos'),  # Incluye el parámetro "categoria"
    path('agregar/<int:medicamento_id>/', views.agregar_medicamento, name='Add'),  # Cambia "producto_id" a "medicamento_id"
    path('eliminar/<int:medicamento_id>/', views.eliminar_medicamento, name='Del'),  # Cambia "producto_id" a "medicamento_id"
    path('restar/<int:medicamento_id>/', views.restar_medicamento, name='Sub'),  # Cambia "producto_id" a "medicamento_id"
    path('limpiar/', views.limpiar_carrito, name='CLS'),
]

crud_virtual/Proyecto/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("app.urls")),
    path("",include("compras.urls")),
    path("",include("CarritoApp.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

crud_virtual/app/urls.py
from django.urls import path
from .import views
from django.contrib import admin


urlpatterns = [
    path('',views.index, name='index'),
    path('quienessomos/',views.quienessomos, name='quienessomos'),

    path('contacto/',views.contacto, name='contacto'),
    path('servicios/',views.servicios, name='servicios'),
    path('preguntasfrecuentes/',views.preguntasfrecuentes, name='preguntasfrecuentes'),
    path('admin/', admin.site.urls, name='admin'),
    path('home/',views.index, name='home'),
    path('login/',views.login, name='login'),
    path('register/', views.register, name='register'),
    path('accounts/profile/', views.index, name='home'),
    path('logout/', views.exit, name="exit"),
]   

crud_virtual/CarritoApp/models.py
from django.db import models

class Medicamento(models.Model):
    id_medicamento = models.AutoField(primary_key=True)
    url = models.CharField( max_length=250)
    nombre_medicamento = models.CharField(max_length=150)
    desc_medicamento = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    precio = models.IntegerField( null=True, blank=True)
    categoria = models.CharField(max_length=33)  # Agregar campo para la categoría

    def precio_con_descuento(self):
        if self.desc_medicamento is not None:
            return self.precio - (self.precio * (self.desc_medicamento / 100))
        else:
            return self.precio

    def __str__(self):
        return f'{self.nombre_medicamento} -> $ {self.precio} (Descuento: {self.desc_medicamento}%)'
    
    class Meta:
        managed = False
        db_table = 'medicamentos'

class Stock(models.Model):
    id_stock = models.AutoField(primary_key=True)
    id_medicamento = models.ForeignKey('Medicamento', models.DO_NOTHING, db_column='id_medicamento')
    cantidad = models.IntegerField()

    def __str__(self):
        return f'{self.id_medicamento.nombre_medicamento} - Cantidad: {self.cantidad}'

    class Meta:
        managed = False
        db_table = 'stock'

crud_virtual/CarritoApp/views.py
from django.shortcuts import render, HttpResponse


from app.models import Direcciones
from .carrito import Carrito
from .models import Medicamento, Stock  # Importa el modelo Medicamento en lugar de Producto
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

def catalogo(request, categoria=None):
    carrito = Carrito(request)
    medicamentos = Medicamento.objects.all()  # Cambia Producto a Medicamento
    ofertas = Medicamento.objects.filter(desc_medicamento__gt=0)  # Cambia descuento a desc_medicamento
    cant_medicamentos = carrito.obtener_cantidad_total()  # Cambia obtener_cantidad_total a obtener_cantidad_total

    if categoria:
        medicamentos = medicamentos.filter(categoria=categoria)

    context = {
        'medicamentos': medicamentos,
        'categoria': categoria,
        'ofertas': ofertas,
        'cant_medicamentos': cant_medicamentos,
    }

    return render(request, 'catalogos.html', context)

@login_required
def carrito(request):
    carrito = Carrito(request)
    cant_medicamentos = carrito.obtener_cantidad_total()  # Cambia obtener_cantidad_total a obtener_cantidad_total

    context = {
        'cant_medicamentos': cant_medicamentos,
    }

    return render(request, 'pagcarrito.html', context)

def detalle(request):
    afiliado = request.user.afiliados
    direccion = Direcciones.objects.get(pk=afiliado.id_direccion)
    cant_medicamentos = Carrito(request).obtener_cantidad_total()

    context = {
        'cant_medicamentos': cant_medicamentos,
        'afiliado': afiliado,
        'direccion': direccion,
    }

    return render(request, 'detalle.html', context)


def tienda(request):
    carrito = Carrito(request)
    cant_medicamentos = carrito.obtener_cantidad_total()

    medicamentos = Medicamento.objects.all()

    context = {
        'medicamentos': medicamentos,
        'cant_medicamentos': cant_medicamentos,
    }

    return render(request, "index.html", context)

def agregar_medicamento(request, medicamento_id):
    carrito = Carrito(request)
    medicamento = Medicamento.objects.get(id_medicamento=medicamento_id)
    cantidad = int(request.POST.get('cantidad', 1))
    carrito.agregar(medicamento, cantidad)
    return redirect(request.META.get('HTTP_REFERER'))


def eliminar_medicamento(request, medicamento_id):
    carrito = Carrito(request)
    medicamento = Medicamento.objects.get(id_medicamento=medicamento_id)
    carrito.eliminar(medicamento)
    return redirect(request.META.get('HTTP_REFERER'))

def restar_medicamento(request, medicamento_id):
    carrito = Carrito(request)
    medicamento = Medicamento.objects.get(id_medicamento=medicamento_id)
    carrito.restar(medicamento)
    return redirect(request.META.get('HTTP_REFERER'))

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect(request.META.get('HTTP_REFERER'))

crud_virtual/CarritoApp/templates/catalogos.html
{% extends 'home.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{% block content %}
<div style="display: flex; justify-content: start; align-items: center; background-color: #333; border-top: 3px solid white; border-bottom: 3px solid white;">
    <div>
        <h2 style="padding: 5px 1rem 0px 1rem; color: orange;">Elige una categoría:</h2>
    </div>
    <div class="dropdown">
        <button class="btn btn-dark dropdown-toggle" style="border: 2px solid white;" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categorías
        </button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Analgésicos' %}">Analgésicos</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Antiinflamatorios' %}">Antiinflamatorios</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Gastrointestinales' %}">Gastrointestinales</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Antibióticos' %}">Antibióticos</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Cardiovasculares' %}">Cardiovasculares</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Diabetes' %}">Diabetes</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Antialérgicos' %}">Antialérgicos</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Psiquiatría' %}">Psiquiatría</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Tiroides' %}">Tiroides</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Antifúngicos' %}">Antifúngicos</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Urología' %}">Urología</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Diuréticos' %}">Diuréticos</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Neurología' %}">Neurología</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Oftalmología' %}">Oftalmología</a></li>
            <li><a class="dropdown-item" href="{% url 'catalogos' categoria='Inmunosupresores' %}">Inmunosupresores</a></li>

            <li><a class="dropdown-item" href="{% url 'catalogos' %}">Todos los medicamentos</a></li>
        </ul>
    </div>
</div>

{% if categoria %}
<div id="centrado">
    <div id="contenido" >
    <h1>Catálogo de {{ categoria }}</h1>
    </div>
  </div>
{% else %}
<div id="centrado">
    <div id="contenido" >
    <h1>Todos los medicamentros</h1>
    </div>
  </div>
{% endif %}

<div class="row justify-content-center">
    {% for medicamento in medicamentos %}
    <div class="ancho-personalizado" style="height: auto; padding: 1rem 1rem;">
        <div class="card card border-dark mb-3">
            <img src="{% static medicamento.url %}" class="card-img-top" style="height: 250px; padding: 2rem;" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ medicamento.nombre_medicamento }}</h5>
                <p class="card-text">{{ medicamento.categoria }}</p>
                <p class="card-text">$ {{ medicamento.precio }}</p>
                {% with medicamento.stock_set.first as stock %}
                {% if stock %}
                    <p class="card-text">En stock: {{ stock.cantidad }}</p>
                {% else %}
                    <p class="card-text">Sin stock</p>
                {% endif %}
            {% endwith %}


            {% with medicamento.stock_set.first as stock %}
            <div>
                <form method="post" action="{% url 'Add' medicamento.id_medicamento %}">
                    {% csrf_token %}
                    <div class="input-group" style="display: flex; align-items: center;">
                        {% if stock and stock.cantidad > 0 %}
                        <button type="button" class="btn btn-secondary btn-minus">-</button>
                        <input type="number" id="cantidad-{{ medicamento.id_medicamento }}" name="cantidad" value="1" min="1" style="max-width: 60px; margin-left: 2px; margin-right: 4px;">
                        <button type="button" class="btn btn-secondary btn-plus">+</button>
                            <button type="submit" class="btn btn-dark" style="margin-left: 10px;">Agregar al carrito</button>
                        {% else %}
                            <button type="button" class="btn btn-dark" style="margin-left: 10px;" disabled>No hay stock</button>
                        {% endif %}
                    </div>
                </form>
            </div>
        {% endwith %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(".btn-plus").click(function () {
            var inputElement = $(this).closest(".input-group").find("input");
            var currentValue = parseInt(inputElement.val());
            inputElement.val(currentValue + 1);
        });

        $(".btn-minus").click(function () {
            var inputElement = $(this).closest(".input-group").find("input");
            var currentValue = parseInt(inputElement.val());
            if (currentValue > 1) {
                inputElement.val(currentValue - 1);
            }
        });
    });
</script>
{% endblock content %}

crud_virtual/CarritoApp/templates/detalle.html
{% extends 'home.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{% block content %}
<style>
    .container {
        background-color: #ffffff;
        margin-top: 20px;
        border: 1px solid #dddddd;
        padding: 20px;
        border-radius: 10px;
    }

    h2 {
        color: #333333;
    }

    table {
        width: 100%;
        margin-bottom: 20px;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid #dddddd;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    .row {
        margin-bottom: 20px;
    }

    label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    .text-center {
        text-align: center;
    }

    .alert-dark {
        background-color: #343a40;
        color: #ffffff;
    }
</style>

<div class="boddy">
    <div class="container">
        <h2 class="text-center">Detalle de Compra</h2>
        <h5 style="text-align: right;"><strong>Fecha de Hoy:</strong> {% now "d-m-Y" %}</h5>

        <!-- Información del Afiliado -->
        {% with afiliado=request.user.afiliados %}
            <div class="row mb-4">
                <h4>Información del Afiliado</h4>
                <div class="col-md-6">
                    <p><strong>Nombre:</strong> {{ afiliado.nombre_afi }}</p>
                    <p><strong>Apellido:</strong> {{ afiliado.apellido_afi }}</p>
                    <p><strong>DNI:</strong> {{ afiliado.dni_afi }}</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Fecha de Nacimiento:</strong> {{ afiliado.fecha_nac_afi }}</p>
                    <p><strong>Teléfono:</strong> {{ afiliado.tel_afi }}</p>
                    <p><strong>Correo:</strong> {{ afiliado.mail_afi }}</p>
                </div>
            </div>

            <div class="row mb-4">
                <h4>Detalles de Envío</h4>
                <div class="col-md-6">
                    <p><strong>Provincia:</strong> Salta</p>
                    <p><strong>Localidad:</strong> Salta Capital</p>
                </div>
                <div class="col-md-6">
                    {% if direccion %}
                        <p><strong>Calle:</strong> {{ direccion.calle }}</p>
                        <p><strong>Número:</strong> {{ direccion.numero }}</p>
                    {% endif %}
                </div>
            </div>
        {% endwith %}

        <!-- Detalles del Carrito -->
        {% if request.session.carrito.items %}
            <h4>Compra</h4>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Subtotal</th>
                </tr>
                </thead>
                <tbody>
                {% for key, value in request.session.carrito.items %}
                    <tr>
                        <td>{{ value.nombre }}</td>
                        <td>{{ value.cantidad }}</td>
                        <td>$ {{ value.acumulado }}</td>
                    </tr>
                {% endfor %}
                <!-- Total del Carrito dentro de la tabla -->
                <tr>
                    <td colspan="2" class="text-right"><strong>Total:</strong></td>
                    <td><strong>$ {{ total_carrito }}</strong></td>
                </tr>
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-dark text-center">Sin Medicamentos</div>
        {% endif %}

        <!-- Botones -->
        <div class="row text-center">
            <div class="col-6"><a href="{% url 'pagcarrito' %}" class="btn btn-danger">Volver al carrito</a></div>
            <div class="col-6"><button onclick="generarPDF()" class="btn btn-warning">Generar PDF</button></div>
        </div>
    </div>
</div>



{% endblock content %}

crud_virtual/CarritoApp/templates/index.html
{% extends 'home.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0/css/bootstrap.min.css">
</head>
<div id="centrado">
    <div id="contenido" >
    <h1>Tienda</h1>
    </div>
  </div>
<div class="continer" style="padding: 0rem 3rem;;">
    
    <div class="row">
        <div class="">
            <div class="row" >
                <div >
                    <div class="row justify-content-center">
                        {% for medicamento in medicamentos %}
                            <div class="ancho-personalizado" style="height: auto; padding: 1rem 1rem;">
                                <div class="card card border-dark mb-3">
                                    <img src="{% static medicamento.url %}" class="card-img-top" style="height: 250px; padding: 2rem;" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ medicamento.nombre_medicamento }}</h5>
                                        <p class="card-text">{{ medicamento.categoria }}</p>
                                        <p class="card-text">$ {{ medicamento.precio }}</p>
                                        
                                        {% with medicamento.stock_set.first as stock %}
                                            {% if stock %}
                                                <p class="card-text">En stock: {{ stock.cantidad }}</p>
                                            {% else %}
                                                <p class="card-text">Sin stock</p>
                                            {% endif %}
                                        {% endwith %}
                    

                                        {% with medicamento.stock_set.first as stock %}
                                        <div>
                                            <form method="post" action="{% url 'Add' medicamento.id_medicamento %}">
                                                {% csrf_token %}
                                                <div class="input-group" style="display: flex; align-items: center;">
                                                    {% if stock and stock.cantidad > 0 %}
                                                    <button type="button" class="btn btn-secondary btn-minus">-</button>
                                                    <input type="number" id="cantidad-{{ medicamento.id_medicamento }}" name="cantidad" value="1" min="1" style="max-width: 60px; margin-left: 2px; margin-right: 4px;">
                                                    <button type="button" class="btn btn-secondary btn-plus">+</button>
                                                        <button type="submit" class="btn btn-dark" style="margin-left: 10px;">Agregar al carrito</button>
                                                    {% else %}
                                                        <button type="button" class="btn btn-dark" style="margin-left: 10px;" disabled>No hay stock</button>
                                                    {% endif %}
                                                </div>
                                            </form>
                                        </div>
                                    {% endwith %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(".btn-plus").click(function () {
            var inputElement = $(this).closest(".input-group").find("input");
            var currentValue = parseInt(inputElement.val());
            inputElement.val(currentValue + 1);
        });

        $(".btn-minus").click(function () {
            var inputElement = $(this).closest(".input-group").find("input");
            var currentValue = parseInt(inputElement.val());
            if (currentValue > 1) {
                inputElement.val(currentValue - 1);
            }
        });
    });
</script>

{% endblock content %}

crud_virtual/CarritoApp/templates/innnn.html
{% extends 'home.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}



{% block content %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0/css/bootstrap.min.css">
</head>
<h2 style="padding: 1rem ">Tienda</h2>
<div class="continer" style="padding: 0rem 3rem;;">
    
    <div class="row">
        <div class="">
            <div class="row" >
                <div >
                    <div class="row">
                        {% for producto in productos %}
                        <div class="ancho-personalizado" style=" height: auto; padding: 1rem 1rem;">
                            <div class="card card border-dark mb-3">
                                <div class="card-body">
                                    <h5 class="card-title">{{ producto.nombre }}</h5>
                                    <p class="card-text">{{ producto.categoria }}</p>
                                    <p class="card-text">$ {{ producto.precio }}</p>
                                    <div>
                                        <form method="post" action="{% url 'Add' producto.id %}">
                                            {% csrf_token %}
                                            <div class="row">
                                                    <input type="number" id="cantidad-{{ producto.id }}" name="cantidad" value="1" min="1" class="form-control">
                                                <button type="submit" class="btn btn-dark mt-3">Agregar al carrito</button>
                                            </div>
                                            <div class="input-group" style="display: flex; align-items: center;">
                                                <button type="button" class="btn btn-secondary btn-minus">-</button>
                                                <input type="number" id="cantidad-{{ producto.id }}" name="cantidad" value="1" min="1" style="max-width: 60px; margin-left: 2px; margin-right: 3px;">
                                                <button type="button" class="btn btn-secondary btn-plus">+</button>
                                                <button type="submit" class="btn btn-dark" style="margin-left: 10px;">Agregar al carrito</button>
                                            </div>

                                        </form>                                      
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(".btn-plus").click(function () {
            var inputElement = $(this).closest(".input-group").find("input");
            var currentValue = parseInt(inputElement.val());
            inputElement.val(currentValue + 1);
        });

        $(".btn-minus").click(function () {
            var inputElement = $(this).closest(".input-group").find("input");
            var currentValue = parseInt(inputElement.val());
            if (currentValue > 1) {
                inputElement.val(currentValue - 1);
            }
        });
    });
</script>

    {% endblock content %}

crud_virtual/CarritoApp/templates/pagcarrito.html
{% extends 'home.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div class="" style="padding: 20px 20px;">
  <div class="alert alert-secondary card border-dark mb-3" role="alert">
    <table class="table table-bordered">
      <thead style="border-collapse: separate; border-radius: 2px; border: 2px solid black">
        <tr>
          <th scope="row" colspan="3" class="text-center">CARRITO DE COMPRAS</th>
        </tr>
        <tr style="border-collapse: separate; border-radius: 2px; border: 2px solid black">
          <th scope="col">NOMBRE</th>
          <th scope="col">PRECIO</th>
          <th scope="col">CANTIDAD</th>
        </tr>
      </thead>
      <tbody>
        {% if request.session.carrito.items %}
        {% for key, value in request.session.carrito.items %}
        <tr>
          <td>{{ value.nombre }}</td>
          <td>$ {{ value.precio }} {{ value.acumulado }}</td>
          <td>
            <a style="text-decoration: none;">  {{ value.cantidad }}</a>
            <a href="{% url 'Add' value.medicamento_id %}" class="badge btn btn-dark badge-dark">+</a>
            <a href="{% url 'Sub' value.medicamento_id %}" class="badge btn btn-dark badge-dark">-</a>
          </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
          <td colspan="3">
            <div class="alert alert-dark text-center">Sin Medicamentos</div>
          </td>
        </tr>
        {% endif %}
        <tr>
          <th scope="row">Total:</th>
          <td colspan="2">$ {{ total_carrito }}</td>
        </tr>
      </tbody>
    </table>
    <hr>
  </div>
  <div class="row text-center">
    <div class="col-6"><a href="{% url 'CLS' %}" class="btn btn-danger">Limpiar</a></div>
    <div class="col-6"><a href="{% url 'detalle' %}" class="btn btn-warning">Hacer compra</a></div>
  </div>
</div>
{% endblock content %}